Feat/bff 1553
MatheusCortez/CRUD-API pull request #1
Opened 2022-02-18 01:07 UTC by MatheusCortez

2022-02-18 01:09 UTC, MatheusCortez commented
Aberto PR Referente a tarefa bff-1553

2022-02-21 14:26 UTC, Jarinha99 commented on src/config/config.ts
> +    }
Opa, aqui seria legal manter um padrão de nome para as propriedades! 

No database você usou PascalCase, no APICEP foi tudo UpperCase mesmo.

Caso não tenha visto desses padrões, dá uma lida rapidinho em PascalCase e camelCase!

2022-02-21 14:30 UTC, Jarinha99 commented on src/services/apicep/apicep.service.ts
> +
Opa, aqui está fora do padrão do resto do código! Em outras services você escreveu sem essa linha em branco, após as chaves, aqui você adicionou elas! Seria legal um padrão só!

Isso vai ser mais "impactante" quando implementar o ESLint, mas ai o porquê pode deixar pra quando chegar essa etapa!

2022-02-21 14:32 UTC, Jarinha99 requested changes
Só alguns padrões para revisar com os comentários que fiz, mas de resto tá aprovado mano!

2022-02-22 14:44 UTC, MatheusCortez commented on src/config/config.ts
> +    }
Apontamentos resolvidos

2022-02-22 19:32 UTC, Jarinha99 approved these changes

2022-02-22 19:33 UTC, merged